=== api-evangelist/google-analytics/json-schema/admin-api-property-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/google-analytics/refs/heads/main/json-schema/admin-api-property-schema.json",
  "title": "Property",
  "description": "A resource message representing a Google Analytics GA4 property.",
  "type": "object",
  "properties": {
    "account": {
      "description": "Immutable. The resource name of the parent account Format: accounts/{account_id} Example: \"accounts/123\"",
      "type": "string"
    },
    "createTime": {
      "description": "Output only. Time when the entity was originally created.",
      "format": "google-datetime",
      "readOnly": true,
      "type": "string"
    },
    "currencyCode": {
      "description": "The currency type used in reports involving monetary values. Format: https://en.wikipedia.org/wiki/ISO_4217 Examples: \"USD\", \"EUR\", \"JPY\"",
      "type": "string"
    },
    "deleteTime": {
      "description": "Output only. If set, the time at which this property was trashed. If not set, then this property is not currently in the trash can.",
      "format": "google-datetime",
      "readOnly": true,
      "type": "string"
    },
    "displayName": {
      "description": "Required. Human-readable display name for this property. The max allowed display name length is 100 UTF-16 code units.",
      "type": "string"
    },
    "expireTime": {
      "description": "Output only. If set, the time at which this trashed property will be permanently deleted. If not set, then this property is not currently in the trash can and is not slated to be deleted.",
      "format": "google-datetime",
      "readOnly": true,
      "type": "string"
    },
    "industryCategory": {
      "description": "Industry associated with this property Example: AUTOMOTIVE, FOOD_AND_DRINK",
      "enum": [
        "INDUSTRY_CATEGORY_UNSPECIFIED",
        "AUTOMOTIVE",
        "BUSINESS_AND_INDUSTRIAL_MARKETS",
        "FINANCE",
        "HEALTHCARE",
        "TECHNOLOGY",
        "TRAVEL",
        "OTHER",
        "ARTS_AND_ENTERTAINMENT",
        "BEAUTY_AND_FITNESS",
        "BOOKS_AND_LITERATURE",
        "FOOD_AND_DRINK",
        "GAMES",
        "HOBBIES_AND_LEISURE",
        "HOME_AND_GARDEN",
        "INTERNET_AND_TELECOM",
        "LAW_AND_GOVERNMENT",
        "NEWS",
        "ONLINE_COMMUNITIES",
        "PEOPLE_AND_SOCIETY",
        "PETS_AND_ANIMALS",
        "REAL_ESTATE",
        "REFERENCE",
        "SCIENCE",
        "SPORTS",
        "JOBS_AND_EDUCATION",
        "SHOPPING"
      ],
      "type": "string"
    },
    "name": {
      "description": "Output only. Resource name of this property. Format: properties/{property_id} Example: \"properties/1000\"",
      "readOnly": true,
      "type": "string"
    },
    "parent": {
      "description": "Immutable. Resource name of this property's logical parent. Note: The Property-Moving UI can be used to change the parent. Format: accounts/{account}, properties/{property} Example: \"accounts/100\", \"properties/101\"",
      "type": "string"
    },
    "propertyType": {
      "description": "Immutable. The property type for this Property resource. When creating a property, if the type is \"PROPERTY_TYPE_UNSPECIFIED\", then \"ORDINARY_PROPERTY\" will be implied.",
      "enum": [
        "PROPERTY_TYPE_UNSPECIFIED",
        "PROPERTY_TYPE_ORDINARY",
        "PROPERTY_TYPE_SUBPROPERTY",
        "PROPERTY_TYPE_ROLLUP"
      ],
      "type": "string"
    },
    "serviceLevel": {
      "description": "Output only. The Google Analytics service level that applies to this property.",
      "enum": [
        "SERVICE_LEVEL_UNSPECIFIED",
        "GOOGLE_ANALYTICS_STANDARD",
        "GOOGLE_ANALYTICS_360"
      ],
      "readOnly": true,
      "type": "string"
    },
    "timeZone": {
      "description": "Required. Reporting Time Zone, used as the day boundary for reports, regardless of where the data originates. If the time zone honors DST, Analytics will automatically adjust for the changes. NOTE: Changing the time zone only affects data going forward, and is not applied retroactively. Format: https://www.iana.org/time-zones Example: \"America/Los_Angeles\"",
      "type": "string"
    },
    "updateTime": {
      "description": "Output only. Time when entity payload fields were last updated.",
      "format": "google-datetime",
      "readOnly": true,
      "type": "string"
    }
  }
}

=== api-evangelist/google-analytics/examples/admin-api-property-example.json
{
  "account": "example_value",
  "createTime": "2026-04-17T12:00:00Z",
  "currencyCode": "USD",
  "deleteTime": "2026-04-17T12:00:00Z",
  "displayName": "Example Analytics Property",
  "expireTime": "2026-04-17T12:00:00Z",
  "industryCategory": "ONLINE_COMMUNITIES",
  "name": "Example Analytics Property",
  "parent": "example_value",
  "propertyType": "PROPERTY_TYPE_SUBPROPERTY"
}
