=== api-evangelist/google-analytics/json-schema/google-analytics-audienceexport-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/AudienceExport",
  "title": "AudienceExport",
  "description": "An audience export is a list of users in an audience at the time of the list's creation. One audience may have multiple audience exports created for different days.",
  "properties": {
    "audience": {
      "description": "Required. The audience resource name. This resource name identifies the audience being listed and is shared between the Analytics Data & Admin APIs. Format: `properties/{property}/audiences/{audience}`",
      "type": "string",
      "example": "example_value"
    },
    "audienceDisplayName": {
      "description": "Output only. The descriptive display name for this audience. For example, \"Purchasers\".",
      "readOnly": true,
      "type": "string",
      "example": "Example Name"
    },
    "beginCreatingTime": {
      "description": "Output only. The time when CreateAudienceExport was called and the AudienceExport began the `CREATING` state.",
      "format": "google-datetime",
      "readOnly": true,
      "type": "string",
      "example": "2026-04-17T12:00:00Z"
    },
    "creationQuotaTokensCharged": {
      "description": "Output only. The total quota tokens charged during creation of the AudienceExport. Because this token count is based on activity from the `CREATING` state, this tokens charged will be fixed once an AudienceExport enters the `ACTIVE` or `FAILED` states.",
      "format": "int32",
      "readOnly": true,
      "type": "integer",
      "example": 42
    },
    "dimensions": {
      "description": "Required. The dimensions requested and displayed in the query response.",
      "items": {
        "$ref": "#/components/schemas/V1betaAudienceDimension"
      },
      "type": "array"
    },
    "errorMessage": {
      "description": "Output only. Error message is populated when an audience export fails during creation. A common reason for such a failure is quota exhaustion.",
      "readOnly": true,
      "type": "string",
      "example": "example_value"
    },
    "name": {
      "description": "Output only. Identifier. The audience export resource name assigned during creation. This resource name identifies this `AudienceExport`. Format: `properties/{property}/audienceExports/{audience_export}`",
      "readOnly": true,
      "type": "string",
      "example": "Example Name"
    },
    "percentageCompleted": {
      "description": "Output only. The percentage completed for this audience export ranging between 0 to 100.",
      "format": "double",
      "readOnly": true,
      "type": "number",
      "example": 75.5
    },
    "rowCount": {
      "description": "Output only. The total number of rows in the AudienceExport result.",
      "format": "int32",
      "readOnly": true,
      "type": "integer",
      "example": 10
    },
    "state": {
      "description": "Output only. The current state for this AudienceExport.",
      "enum": [
        "STATE_UNSPECIFIED",
        "CREATING",
        "ACTIVE",
        "FAILED"
      ],
      "readOnly": true,
      "type": "string",
      "example": "STATE_UNSPECIFIED"
    }
  },
  "type": "object"
}

=== api-evangelist/google-analytics/examples/data-api-audience-export-example.json
{
  "audience": "example_value",
  "audienceDisplayName": "Example Name",
  "beginCreatingTime": "2026-04-17T12:00:00Z",
  "creationQuotaTokensCharged": 42,
  "dimensions": [
    {
      "dimensionName": "Example Analytics Property"
    }
  ],
  "errorMessage": "example_value",
  "name": "Example Name",
  "percentageCompleted": 75.5,
  "rowCount": 10,
  "state": "STATE_UNSPECIFIED"
}
